"""add_execution_state

Revision ID: bab08920a458
Revises: 33bb243efeb7
Create Date: 2026-09-25 02:55:44.951240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab08920a458'
down_revision: Union[str, None] = '33bb243efeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('execution_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows') as batch_op:
        batch_op.drop_column('execution_state')
    # ### end Alembic commands ###
